### ISSUE TITLE
5V power from the charger?

### ISSUE THREAD

**Issue by NetJaro** [assembly12/Foxess-T-series-ESPHome-Home-Assistant#11]
Hi!

First of all - thank you for this project :)

Can I use power supply from 5V charger? Without dc/dc  buck converter and without 12V+ (7 pin) in inventer? 
I would like to use EPS32 to something more - it should be turn on always :) 

Thanks!
Marcin

**Comment by assembly12** [comment]
Hi,
it should be possible, however you would need to connect the ground of the 5V powersupply to the ground of the inverter. I've not tested it and over on the HA forum, someone was trying to do the same but had some issues.

If you power the ESP from the 12v from the inverter it will always be powered, though. Its only the communication that gets interrupted at night. The 12v and the ESP always work! So in my opinion this really is the nicest option.

**Comment by giedriuskilcauskas** [comment]
I can confirm that it works fine this way. I have ESP32 powered with USB
