### ISSUE TITLE
Why the custom code rather than ESPHome modbus entries?

### ISSUE THREAD

**Issue by titchy** [assembly12/Foxess-T-series-ESPHome-Home-Assistant#22]
I am just starting out on this and am interested to know what the reasoning was to go with the additional code rather than the ESPHome modbus_controller platform?
Thank you for a very handy piece of code, it will once I get it working make my setup much better.

**Comment by assembly12** [comment]
Even though Foxess calls it "modbus", it isn't really modbus protocol, but rather a rs485 serial communication protocol.
It doesn't work with the ESPHome modbus component, so the additional code is necessary.
