### ISSUE TITLE
RFE bit more detail on the wiki page

### ISSUE THREAD

**Issue by titchy** [assembly12/Foxess-T-series-ESPHome-Home-Assistant#4]
The Wiki says, "Make sure to set the pot on the buck converter to 5V before wiring it up". Now I did electronics at school some 30 years ago so can just about figure out what this entails, but I think a little more detail would be nice for those with less knowledge. 
Also my rs485 to TTL module has the same number of pins as the one in your image but instead labels them as VCC TXD RXD and GND. This has kept me busy looking at docs for some time so a little extra detail around the TTL side of the module on the WIKi would be very handy for new users.
Thank you for putting in all the effort on this it is so much better than using the cloud interface!

**Comment by assembly12** [comment]
Hi and thanks for your feedback.
I elaborated some more on the dailing of the potentiometer.

On the other hand, some basic knowledge is either assumed to be present or easily accessable by googling.
If someone is still stuck at a certain point, just ask here and i'll be more than happy to help!
