### ISSUE TITLE
Update interval

### ISSUE THREAD

**Issue by lkuznicki** [assembly12/Foxess-T-series-ESPHome-Home-Assistant#9]
Hi
Firstly many thanks for this - works perfectly with T8 G3 inverter.
Could you please advice if it is possible to change update interval?

**Comment by assembly12** [comment]
Hi,
the update inverval can be increased. But unfortunately it can't be decreased.
The inverter sends a message every 90 seconds (or 120 seconds depending on the inverter-firmware).
The update inverval is therefore capped at 1.5 minutes (or 2 minutes).

**Comment by lkuznicki** [comment]
Many thanks for rapid answer. This is exactly what I thought but had hope.
I wanted decrease.
